nome = str(input('nome?'))
sobrenome =  str(input('sobrenome?'))
idade = int(input('idade?'))
ano_de_nascimento = str(input('data de nascimento '))
maior_de_idade = idade >= 18
altura = float(input('altura metros:'))
print('Nome',nome)
print('Sobrenome', sobrenome)
print('idade', idade)
print('maior de idade?', maior_de_idade)
print('altura em metros:', altura)